- server/src/main/java/wap/web2/server/domain/Image.java
- server/src/main/java/wap/web2/server/domain/Project.java
- closed: #10 
- Project, Image 엔티티 클래스
> featre : Project, Image엔티티

- server/src/main/java/wap/web2/server/domain/Comment.java
- server/src/main/java/wap/web2/server/domain/Project.java
- server/src/main/java/wap/web2/server/domain/TeamMember.java
- server/src/main/java/wap/web2/server/domain/TechStack.java
- server/src/main/java/wap/web2/server/domain/TechStackType.java
- closed: #12
- 프로젝트의 생성 및 세부 항목과 같은 전반적인 기능에 필요한 Comment, TeamMember, TechStack Entity 생성
- Project와 각각의 entity에 대해 양방향 연걸
TechStack의 techStackType에 enum을 사용하여 구현하였습니다. 
> String으로 했을 때 오기입으로 인한 오류를 줄일 수 있게 타입 안정성을 확보하는게 중요하다고 생각했습니다.(물론 잘못 입력받을 일은 없겠지만) 
> 
> 그리고 나중에 발생할 수 있는 여러 줄의 if문 대신 switch-case를 활용하면 더 좋을것 같아서 일단 이렇게 작성했씁니다.
1h
> feature: Comment, TeamMember, TechStack 도메인 개발 (#12)

- client/src/assets/ProjectCreation/ProjectForm.css
- client/src/components/ProjectCreation/ProjectForm.js
- closed: #21 21
- 가독성을 위해 기본 UI 구현
> feature: #21

- server/src/main/java/wap/web2/server/domain/TechStack.java
- server/src/main/java/wap/web2/server/domain/TechStackName.java
- server/src/main/java/wap/web2/server/domain/TechStackType.java
- closed: #19 
- 고민 끝에 Project와 TechStack을 일대다 매핑으로 하기로 했습니다
- 정해진 값인 TechStackName과 TechStackType은 enum으로 생성하였습니다.
- enum값은 api명세에 추가해뒀습니다(명시된 값들만 get하고 post할 수 있어요)
> [Server] feature: TechStack 엔티티 생성 (#19)

- server/src/main/java/wap/web2/server/controller/TechStackController.java
- server/src/main/java/wap/web2/server/payload/response/TechStackInfoResponse.java
- server/src/main/java/wap/web2/server/payload/response/TechStackResponse.java
- closed: #29 
- enum으로 고정값이라 Service와 Repository 이용 안함
- 이미지는 추후에 추가할 예정
> feature : 기술스택 GET

- client/src/assets/ProjectCreation/InputForm.css
- client/src/assets/ProjectCreation/ProjectForm.module.css
- client/src/assets/ProjectCreation/RadioButton.css
- client/src/assets/ProjectCreation/TechStackSelector.css
- client/src/assets/ProjectCreation/YearSelector.css
- client/src/components/ProjectCreation/ProjectForm.js
- client/src/components/ProjectCreation/TechStackList.js
- client/src/components/ProjectCreation/TechStackSelector.js
- client/src/hooks/ProjectCreation/useProjectForm.js
- client/src/index.js
> [Client] feature: 프로젝트 기술스택 선택 컴포넌트 구현 및 UI 완성 (#32)

- client/src/assets/ProjectCreation/TeamMemberInputForm.css
- client/src/assets/ProjectCreation/TechStackSelector.css
- client/src/assets/ProjectCreation/YearSelector.css
- client/src/components/ProjectCreation/ProjectForm.js
- client/src/components/ProjectCreation/TeamMemberInputForm.js
- client/src/components/ProjectCreation/TechStackList.js
- client/src/components/ProjectCreation/TechStackSelector.js
- client/src/hooks/ProjectCreation/useProjectForm.js
> [Client] feature: 프로젝트 팀원 선택 컴포넌트 구현 및 UI 완성 (#36)

- client/src/index.js
- client/src/pages/menu/CreatePage.js
> feature : 프로젝트 생성 페이지 연결

- client/src/assets/ProjectCreation/InputForm.css
- client/src/assets/ProjectCreation/TeamMemberInputForm.css
- client/src/assets/ProjectCreation/TechStackSelector.css
- client/src/assets/ProjectCreation/YearSelector.css
- client/src/components/ProjectCreation/ProjectForm.js
- client/src/components/ProjectCreation/TeamMemberInputForm.js
- client/src/components/ProjectCreation/TechStackList.js
- client/src/components/ProjectCreation/TechStackSelector.js
- client/src/hooks/ProjectCreation/useProjectForm.js
- client/src/index.js
- client/src/pages/ProjectCreation/ProjectCreationPage.js
- client/src/pages/menu/CreatePage.js
> [Client] feature : 프로젝트 생성 페이지 구현 (#43)

- client/src/assets/ProjectCreation/RadioButton.module.css
- client/src/assets/ProjectCreation/TeamMemberInputForm.module.css
- client/src/assets/ProjectCreation/TechStackSelector.module.css
- client/src/assets/ProjectCreation/TextInputForm.module.css
- client/src/components/ProjectCreation/ProjectForm.js
- client/src/components/ProjectCreation/RadioButton.js
- client/src/components/ProjectCreation/TeamMemberInputForm.js
- client/src/components/ProjectCreation/TechStackSelector.js
- client/src/components/ProjectCreation/TextInputForm.js
> [Client] refactor : css 파일 모듈화 (#54)

- client/src/components/ProjectDetail/ProjectDetailForm.js
> [Client] fix : 프로젝트 정보 받아오는 api 에러 해결 (#63)

- client/src/assets/ProjectCreation/InputPin.module.css
- client/src/assets/ProjectCreation/ProjectForm.module.css
- client/src/assets/ProjectCreation/RadioButton.module.css
- client/src/assets/ProjectCreation/TextInputForm.module.css
- client/src/assets/ProjectCreation/YearSelector.css
- client/src/components/ProjectCreation/InputPin.js
- client/src/components/ProjectCreation/ProjectForm.js
- client/src/hooks/ProjectCreation/useProjectForm.js
> [Client] feature : 프로젝트 생성페이지 인증번호 입력 칸 추가 (#65)

- client/src/App.css
- client/src/App.js
- client/src/assets/Main/Main.module.css
- client/src/index.js
- client/src/pages/MainPage.js
> [Client] feature : 메인페이지 구현 (#69)

- client/src/App.css
> [Client] fix : 디자인 관련 오류 수정 (#68)

- server/src/main/java/wap/web2/server/payload/ImageDto.java
- server/src/main/java/wap/web2/server/payload/TeamMemberDto.java
- server/src/main/java/wap/web2/server/payload/TechStackDto.java
- server/src/main/java/wap/web2/server/payload/response/ProjectDetailsResponse.java
- closed: #75
- 각 필드를 Dto로 바꾸어서 오류 수정완료하였습니다.
- postman으로 확인했는데 잘 작동합니다 :)
> [Server] fix: project_id로 projectDetails를 조회할 때 발생하는 Project 데이터의 재귀적 호출을 수정 (#75)

- server/src/main/java/wap/web2/server/controller/ProjectController.java
- server/src/main/java/wap/web2/server/domain/Project.java
- server/src/main/java/wap/web2/server/payload/request/ProjectCreateRequest.java
- server/src/main/java/wap/web2/server/repository/ProjectRepository.java
- server/src/main/java/wap/web2/server/service/ProjectService.java
- closed: #72 
> 프로젝트 수정하기
> 
- 수정하기 버튼 클릭 : 수정페이지로 넘어가고 프런트에서 프로젝트 상세정보를 get으로 던져줘서 사용자가 자기가 작성했던 내용에 이어서 수정할 수 있게함
- 수정완료 버튼 클릭 : 이 PUT API가 적용되어 기존의 projectId에 해당하는 프로젝트의 데이터가 수정됨
- api명세서
> feature : 수정

- client/src/components/ProjectDetail/ProjectDetailForm.js
- client/src/hooks/ProjectDetail/useProjectDetailForm.js
> [Client] fix : 프로젝트 상세 정보 받아오는 과정에서의 오류 해결 (#79)

- client/src/components/ContentBox.js
> [Client] chore: 환경변수 파일에 프록시 서버 설정 (#89)

- client/src/components/ProjectCreation/ProjectForm.js
- client/src/components/ProjectCreation/TechStackSelector.js
- client/src/components/ProjectDetail/ProjectDetailForm.js
> [Client] refactor: 리다이렉트를 위해 프록시 주소 설정 (#95)

- client/src/App.js
- client/src/assets/transition.css
- client/src/components/ContentBox.js
- client/src/components/Header.js
- client/src/pages/MainPage.js
> [Client] feature : 세부적인 기능 추가 (#97)

- client/package.json
- client/src/App.js
- client/src/components/Vote/VoteForm.js
- client/src/pages/VotePage.js
> [Client] feature: 임의 투표페이지 생성 #99

- client/src/assets/Main/Main.module.css
> [Client] chore: 환경변수 파일 속 프록시 서버 주소 변경 (#104)

- server/src/main/java/wap/web2/server/controller/ProjectController.java
- server/src/main/java/wap/web2/server/payload/request/ProjectCreateRequest.java
- server/src/main/java/wap/web2/server/service/ProjectService.java
- closed: #106 
- 프로젝트 등록 시 왑회원만 아는 비밀번호를 입력해야 등록됨
- application.properties 변경사항 있음
> feature : 등록 시 비밀번호

- server/src/main/java/wap/web2/server/controller/ProjectController.java
- server/src/main/java/wap/web2/server/payload/request/ProjectCreateRequest.java
- server/src/main/java/wap/web2/server/service/ProjectService.java
Reverts pknu-wap/2024_2_WEB_2#107
> Revert "feature : 등록 시 비밀번호"

- server/src/main/java/wap/web2/server/controller/ProjectController.java
- server/src/main/java/wap/web2/server/service/ProjectService.java
- closed: #103 
- 프로젝트를 작성한 사용자만 프로젝트를 삭제할 수 있다.
- 삭제가 성공할 시 NO_CONTENT가 전송된다.
> [Server] feat: 프로젝트를 삭제하는 기능 추가 (#103)

- client/src/assets/Vote/ProjectVote.module.css
- client/src/components/Vote/VoteForm.js
- client/src/components/Vote/VoteProjectList.js
- client/src/hooks/Projectvote/useProjectVoteForm.js
> [Client] feature: 프로젝트 투표 페이지 구현 (#113)

- client/src/components/ProjectCreation/InputPin.js
- client/src/components/ProjectCreation/ProjectForm.js
- client/src/hooks/ProjectCreation/useProjectForm.js
> [Client] feature: 프로젝트 생성 부분에 비밀번호 필드 추가 (#119)

- client/package-lock.json
- client/package.json
- client/src/components/ProjectCreation/ProjectForm.js
> [Client] feature : 로그인 요청헤더에 토큰 추가 (#122)

- client/src/App.js
- client/src/components/Login/Callback.js
- client/src/components/Login/ProtectedPage.js
> [Client] chore: 프록시 서버에 일치하도록 api 경로 변경 (#125)

- client/src/components/Header.js
- client/src/pages/menu/Login.js
> [Client] fix: 배포 환경에서 로그인되지 않는 문제 해결 (#130)

- server/src/main/java/wap/web2/server/repository/ProjectRepository.java
- server/src/main/java/wap/web2/server/service/ProjectService.java
- closed: #133 
- 프로젝트 목록보기에서 프로젝트 등록한 최신순으로 리턴
> modify : 프로젝트 목록보기 최신순으로

- server/src/main/java/wap/web2/server/domain/Project.java
- closed: #138
- 불필요한 추가 DDL 설정을 없앤다.
- vote를 ProjectCreateRequest.toEntity에서 빌더로 생성할 때 값을 넣어줌으로써 기본값이 0이 되도록 한다.
> [Server] refactor: 기존 Project 엔티티와 동일하도록 수정(#138)

- client/src/assets/ProjectCreation/ProjectForm.module.css
- client/src/components/ProjectCreation/ImageUploader.js
- client/src/components/ProjectCreation/ProjectForm.js
- client/src/hooks/ProjectCreation/useProjectForm.js
> [Client] modify : 프로젝트 등록 시 이미지 삭제 기능 추가 (#140)

- client/src/App.css
- client/src/components/Header.js
- closed: #144 
헤더 x안나오는것 해결
카테고리에 마진 주기
> fix : 헤더 x, 해결

- server/src/main/java/wap/web2/server/controller/CommentController.java
- server/src/main/java/wap/web2/server/domain/Comment.java
- server/src/main/java/wap/web2/server/ouath2/config/SecurityConfig.java
- server/src/main/java/wap/web2/server/payload/CommentDto.java
- server/src/main/java/wap/web2/server/payload/request/CommentCreateRequest.java
- server/src/main/java/wap/web2/server/repository/CommentRepository.java
- server/src/main/java/wap/web2/server/service/CommentService.java
- closed: #146 
- 프로젝트 상세보기에서 익명으로 댓글작성
- 닉네임과 비밀번호와 내용 입력
- 프로젝트 상세보기 api 변경사항 있음
- 댓글에 password 필드 반환 추가
> [Server] feature : 익명댓글 작성

- server/src/main/java/wap/web2/server/controller/CommentController.java
- server/src/main/java/wap/web2/server/ouath2/config/SecurityConfig.java
- server/src/main/java/wap/web2/server/payload/request/CommentDeleteRequest.java
- server/src/main/java/wap/web2/server/service/CommentService.java
- closed: #148 
- 작성때 비밀번호를 통해 댓글 작성한것 삭제
> feature : 댓글삭제

- client/src/App.css
- client/src/components/Header.js
- client/src/components/Login/Callback.js
- client/src/components/Menu.js
- closed: #124 
로그인 로그아웃 버튼 메뉴바로 이동
디자인은 조금더 상의해야할듯
> fix : 로그인 로그아웃 버튼 디자인

- client/src/components/Menu.js
- closed: #152 
프로젝트 생성 및 투표 접근제한
> [client] feature: 프로젝트 생성 및 투표 접근제한(#152)

- client/src/components/Vote/VoteForm.js
> [Client] feature : 프로젝트 투표 API 연동 (#150)

- client/src/assets/ProjectCreation/TeamMemberInputForm.module.css
- client/src/components/ProjectCreation/ProjectFormNew.js
- client/src/components/ProjectCreation/TeamMemberInputForm.js
- client/src/hooks/ProjectCreation/useProjectForm.js
> [Client] feature : 프로젝트 생성폼에서 팀원 삭제 버튼 구현 (#160)

- client/src/assets/Main/Main.module.css
- client/src/assets/ProjectCreation/ProjectForm.module.css
- client/src/assets/ProjectCreation/TeamMemberInputForm.module.css
- client/src/components/FloatingButton.js
- client/src/components/ProjectCreation/TeamMemberInputForm.js
- client/src/pages/ProjectPage.js
> [Client] feature: 돌아가기 플로팅 버튼 (#162)

- client/src/App.js
- client/src/assets/ProjectDetail/EditButton.module.css
- client/src/assets/ProjectDetail/ProjectDetailForm.module.css
- client/src/components/ProjectCreation/ProjectFormNew.js
- client/src/components/ProjectDetail/EditButton.js
- client/src/components/ProjectDetail/ProjectDetailForm.js
> [Client] fix : 프로젝트 수정 400 오류 해결 (#157)

- client/src/App.css
- client/src/assets/Main/Main.module.css
- client/src/components/ProjectCreation/ProjectFormNew.js
- client/src/components/Vote/VoteForm.js
- client/src/pages/Home.js
- client/src/pages/ProjectDetailPage.js
- client/src/pages/VotePage.js
> [Client] modify : 사용의 편의성을 위한 기능 수정 (#168)

- client/src/App.css
- client/src/assets/Main/Main.module.css
- client/src/assets/ProjectCreation/ProjectForm.module.css
- client/src/assets/ProjectDetail/EditButton.module.css
- client/src/assets/ProjectDetail/ProjectDetailForm.module.css
- client/src/assets/Vote/ProjectVote.module.css
- client/src/components/ContentBox.js
- client/src/components/ProjectCreation/ImageUploader.js
- client/src/components/ProjectCreation/ProjectFormNew.js
- client/src/components/ProjectDetail/ProjectDetailForm.js
- client/src/components/Vote/VoteForm.js
- client/src/pages/MainPage.js
> [Client] modify: 로그인 시에만 수정버튼 보이도록 수정 (#170)

- client/src/App.css
- client/src/App.js
- client/src/components/Menu.js
- client/src/components/ProjectCreation/ProjectFormNew.js
- client/src/components/ProjectDetail/ProjectDetailForm.js
> [Client] feature: 투표 페이지 이동 제한 설정 (#173)

- client/src/components/ProjectCreation/ProjectFormNew.js
> [Client] modify : 프로젝트 정보 입력필드 글자 수 제한 수정 (#177)

- client/src/App.css
- closed: #179
fix : 메뉴바 모바일 화면에 맞게 수정
> [Client] fix: 메뉴바 모바일 규격에 맞게 수정(#179)

- server/src/main/java/wap/web2/server/payload/response/ProjectUpdateDetailsResponse.java
- closed: #184 
- 수정 페이지 이동api 에서 기술스택은 get으로 반환 안함
> [Server] modify : 수정페이지 기술스택 반환 제외

- client/src/assets/Main/Main.module.css
- client/src/assets/ProjectDetail/Comments/Comments.module.css
- client/src/assets/ProjectDetail/Comments/CommentsList.module.css
- client/src/assets/ProjectDetail/ProjectDetailForm.module.css
- client/src/components/ProjectDetail/Comments/Comments.js
- client/src/components/ProjectDetail/Comments/CommentsList.js
- client/src/components/ProjectDetail/ProjectDetailForm.js
> [Client] feature : 댓글 컴포넌트 구현 (#182)

- client/public/index.html
- client/src/App.js
- client/src/assets/ProjectCreation/TeamMemberInputForm.module.css
- client/src/assets/ProjectDetail/ProjectDetailForm.module.css
- client/src/components/ContentBox.js
- client/src/components/ProjectDetail/ProjectDetailForm.js
> [Client] modify : 기술 스택, 팀원 컴포넌트 css 수정 (#188)

- client/src/assets/Filter/Type.css
- client/src/components/ContentBox.js
- closed: #186 
프로젝트 페이지 상단에 type별 분류 가능
> [Client] feature : 프로젝트 필터(#186)

- client/src/components/ContentBox.js
> [Client] modify : 로그인 하지 않아도 목록 리스트 보이도록 수정 (#194)

- server/src/main/java/wap/web2/server/domain/Comment.java
- closed: #196 
- 댓글 작성 허용 글자수 늘림
> [Server] modify : 댓글내용 허용 글자수 늘리기

- client/package-lock.json
- client/package.json
- client/public/index.html
> [Client] fix : 배포 빌드 에러 해결 (#200)

- package-lock.json
- package.json
> [Client] fix : 배포 빌드 에러 해결 #202

- client/src/pages/Home.js
- client/src/pages/ProjectDetailPage.js
- client/src/pages/ProjectPage.js
- client/src/pages/VotePage.js
> [Client] modify : 플로팅버튼 다 삭제 (#205)

- client/src/assets/Filter/Type.css
- client/src/components/ContentBox.js
- closed: #204
프로젝트 유형 필터 옆에 학기 필터도 생성
> feature : 학기구분

- client/src/pages/Home.js
- client/src/pages/ProjectDetailPage.js
- client/src/pages/ProjectPage.js
- client/src/pages/VotePage.js
- client/src/pages/menu/Map.js
> [Client] modify : 플로팅버튼 다 삭제 (#209)

- server/src/main/java/wap/web2/server/domain/TechStackName.java
- server/src/main/java/wap/web2/server/domain/TechStackType.java
- server/src/main/java/wap/web2/server/payload/response/TechStackInfoResponse.java
> [Server] refactor : 기술스택 리스트 추가

- client/src/assets/Vote/ProjectVote.module.css
- client/src/components/Vote/VoteForm.js
- client/src/components/Vote/VoteProjectList.js
> [Client] modify : 투표페이지 디자인 수정 (#218)

- client/src/components/Login/Callback.js
- client/src/components/Login/ProtectedPage.js
- client/src/components/Menu.js
- client/src/components/ProjectCreation/ProjectForm.js
- client/src/components/ProjectCreation/ProjectFormNew.js
- client/src/components/ProjectCreation/TechStackSelector.js
- client/src/components/ProjectDetail/Comments/Comments.js
- client/src/components/ProjectDetail/Comments/CommentsList.js
- client/src/components/ProjectDetail/EditButton.js
- client/src/components/ProjectDetail/ProjectDetailForm.js
- client/src/components/Vote/VoteForm.js
- client/src/components/Vote/VoteProjectList.js
> modify : 프록시 서버도된 api 경로를 그냥 서버 경로로 변경

- server/src/main/java/wap/web2/server/comment/controller/CommentController.java
- server/src/main/java/wap/web2/server/comment/dto/CommentDto.java
- server/src/main/java/wap/web2/server/comment/service/CommentService.java
- server/src/main/java/wap/web2/server/config/WebMvcConfig.java
- server/src/main/java/wap/web2/server/exception/ResourceNotFoundException.java
- server/src/main/java/wap/web2/server/member/controller/UserController.java
- server/src/main/java/wap/web2/server/member/dto/UserResponse.java
- server/src/main/java/wap/web2/server/project/controller/TechStackController.java
- server/src/main/java/wap/web2/server/project/dto/response/ProjectUpdateDetailsResponse.java
- server/src/main/java/wap/web2/server/project/dto/response/TechStackInfoResponse.java
- server/src/main/java/wap/web2/server/project/dto/response/TechStackResponse.java
- server/src/main/java/wap/web2/server/project/entity/Image.java
- server/src/main/java/wap/web2/server/project/entity/TechStack.java
- server/src/main/java/wap/web2/server/util/CookieUtils.java
- 전체 코드 공백 리팩토링 진행
- 이전 swagger 작업을... 브랜치 이동을 안하고 해버렸네요
- closed: #228
- 스웨거 사용 가능 하도록 설정 파일 생성
- 카카오 로그인 시 프로필 사진은 안받아오도록 수정
> [Server] refactor: 공백 제거 또는 추가 #228

- server/src/main/java/wap/web2/server/comment/controller/CommentController.java
- server/src/main/java/wap/web2/server/comment/dto/CommentDto.java
- server/src/main/java/wap/web2/server/comment/dto/request/CommentCreateRequest.java
- server/src/main/java/wap/web2/server/comment/entity/Comment.java
- server/src/main/java/wap/web2/server/comment/service/CommentService.java
- closed: #232 
- 댓글에 필요한 내용을 추가하고 필요없는 내용 삭제
> [Server] fix: 코멘트 관련 로직 수정

- server/src/main/java/wap/web2/server/aws/AwsUtils.java
- server/src/main/java/wap/web2/server/project/service/ProjectService.java
- server/src/main/resources/application.yml
참고하십쇼!
사진처럼 프로젝트마다 디렉토리가 생성되고, 이미지가 저장되도록 하였습니다.
> 각 프로젝트의 디렉토리에 이미지가 저장되도록 변경

- client/src/components/ContentBox.js
- client/src/components/Menu.js
- client/src/components/ProjectDetail/Comments/Comments.js
- client/src/components/ProjectDetail/Comments/CommentsList.js
- client/src/index.js
- closed: #235
- 댓글 작성 및 삭제 시 token 사용하도록 수정
25.05.21~05.21
> [Client] modify : 댓글 작성 및 수정시 token 사용하도록 수정

- server/src/main/java/wap/web2/server/project/controller/ProjectController.java
- server/src/main/java/wap/web2/server/project/dto/request/ProjectCreateRequest.java
- server/src/main/java/wap/web2/server/project/dto/response/ProjectDetailsResponse.java
- server/src/main/java/wap/web2/server/project/dto/response/ProjectUpdateDetailsResponse.java
- server/src/main/java/wap/web2/server/project/entity/Project.java
- server/src/main/java/wap/web2/server/project/repository/ProjectRepository.java
- server/src/main/java/wap/web2/server/project/service/ProjectService.java
- server/src/main/java/wap/web2/server/vote/controller/VoteController.java
- server/src/main/java/wap/web2/server/vote/dto/VoteInfoResponse.java
- server/src/main/java/wap/web2/server/vote/dto/VoteRequest.java
- server/src/main/java/wap/web2/server/vote/dto/VoteResultResponse.java
- server/src/main/java/wap/web2/server/vote/entity/Vote.java
- server/src/main/java/wap/web2/server/vote/repository/VoteRepository.java
- server/src/main/java/wap/web2/server/vote/service/VoteService.java
- closed: #238 
- 투표 기능 재 구성 및 구현 했습니다.
- 백엔드 단에서만 분기 처리하는 로직은 복잡한 것 같아서 이후 프론트와 api논의가 필요함
> [Server] feat: 투표 기능 구현

- server/src/main/java/wap/web2/server/project/entity/Image.java
- server/src/main/java/wap/web2/server/project/entity/Project.java
> [Server] 이미지 주소를 저장하기 위해 컬럼의 최대크기를 늘림

- server/src/main/java/wap/web2/server/config/SwaggerConfig.java
- server/src/main/resources/application.yml
> [Server] refactor: swagger 요청 주소를 https 서버 주소로 변경

- server/src/main/java/wap/web2/server/config/SwaggerConfig.java
> [Server] fix: https서버 주소를 swagger에 등록

- server/src/main/resources/application.yml
> fix: https서버 주소를 swagger에 등록

- server/src/main/java/wap/web2/server/aws/AwsUtils.java
- server/src/main/java/wap/web2/server/project/controller/ProjectController.java
- server/src/main/java/wap/web2/server/project/dto/request/ProjectRequest.java
- server/src/main/java/wap/web2/server/project/entity/Image.java
- server/src/main/java/wap/web2/server/project/entity/Project.java
- server/src/main/java/wap/web2/server/project/repository/ImageRepository.java
- server/src/main/java/wap/web2/server/project/repository/ProjectRepository.java
- server/src/main/java/wap/web2/server/project/service/ProjectService.java
- 기존에 있던 프로젝트 이미지 수정 방법을 제거하였습니다.
- 삭제해야할 이미지 List를 받고, 이를 aws s3에서 제거합니다.
- 추가할 이미지 List를 받고, 이를 프로젝트 이미지에 추가합니다.
> [Server] update project image

- client/src/components/ProjectCreation/ProjectFormNew.js
- client/src/components/ProjectDetail/ProjectDetailForm.js
- client/src/hooks/ProjectCreation/useProjectForm.js
- closed: #253
- 이미지 삭제 시 삭제 이미지를 removal이라는 리스트에 담아서 보내도롣 수정
> fix : 이미지 삭제시 삭제한 주소 리스트에 담아서 보내도록 수정

- server/src/main/java/wap/web2/server/member/controller/UserController.java
- server/src/main/java/wap/web2/server/member/entity/Role.java
- server/src/main/java/wap/web2/server/member/entity/User.java
- server/src/main/java/wap/web2/server/member/service/UserService.java
- server/src/main/java/wap/web2/server/ouath2/config/SecurityConfig.java
- server/src/main/resources/application.yml
- closed: #258 
- 회원은 member or guest 2가지 유형으로 존재하도록  설계함
> feat: 회원 구분 api 구현

- client/src/components/Menu.js
- client/src/pages/ProjectPage.js
- client/src/pages/VotePage.js
- closed: #269 
토큰 만료시 투표페이지 접근되는 오류 해결
> [Client] fix : 토큰 만료 여부 확인 추가

- client/src/App.js
- client/src/assets/ProjectCreation/ProjectForm.module.css
- client/src/assets/RoleSelect.module.css
- client/src/components/Login/Callback.js
- client/src/pages/RoleSelectPage.js
- closed: #271
회원 구분 페이지를 구현함
- 질문에 예 클릭 시 member 로, 아니오 클릭 시 guest로 등록됨
> [Client] feature : 회원 구분 페이지 구현

- server/src/main/java/wap/web2/server/ouath2/config/AppProperties.java
- server/src/main/java/wap/web2/server/ouath2/config/SecurityConfig.java
- server/src/main/java/wap/web2/server/ouath2/controller/AuthController.java
- server/src/main/java/wap/web2/server/ouath2/payload/ApiResponse.java
- server/src/main/java/wap/web2/server/ouath2/payload/AuthResponse.java
- server/src/main/java/wap/web2/server/ouath2/payload/LoginRequest.java
- server/src/main/java/wap/web2/server/ouath2/payload/SignUpRequest.java
- server/src/main/java/wap/web2/server/ouath2/security/CustomUserDetailsService.java
- server/src/main/java/wap/web2/server/ouath2/security/RestAuthenticationEntryPoint.java
- server/src/main/java/wap/web2/server/ouath2/security/TokenAuthenticationFilter.java
- server/src/main/java/wap/web2/server/ouath2/security/TokenProvider.java
- server/src/main/java/wap/web2/server/ouath2/security/UserPrincipal.java
- server/src/main/java/wap/web2/server/ouath2/security/oauth2/CustomOAuth2UserService.java
- server/src/main/java/wap/web2/server/ouath2/security/oauth2/HttpCookieOAuth2AuthorizationRequestRepository.java
- server/src/main/java/wap/web2/server/ouath2/security/oauth2/OAuth2AuthenticationFailureHandler.java
- server/src/main/java/wap/web2/server/ouath2/security/oauth2/OAuth2AuthenticationSuccessHandler.java
- server/src/main/java/wap/web2/server/ouath2/security/oauth2/user/KakaoOAuth2UserInfo.java
- server/src/main/java/wap/web2/server/ouath2/security/oauth2/user/OAuth2UserInfo.java
- server/src/main/java/wap/web2/server/ouath2/security/oauth2/user/OAuth2UserInfoFactory.java
- server/src/main/java/wap/web2/server/project/controller/ProjectController.java
- server/src/main/java/wap/web2/server/project/dto/request/ProjectAppliesRequest.java
- server/src/main/java/wap/web2/server/project/dto/response/ProjectAppliesResponse.java
- server/src/main/java/wap/web2/server/project/entity/Project.java
- server/src/main/java/wap/web2/server/project/repository/ProjectApplyRepository.java
- server/src/main/java/wap/web2/server/project/service/ApplyService.java
- server/src/test/java/wap/web2/server/project/service/ApplyRequestServiceTest.java
- server/src/test/java/wap/web2/server/project/service/ApplyServiceTest.java
- closed: #276 
- 지원자 정보 보기 api
> feat: 자신의 팀에 지원한 지원자의 정보를 볼 수 있다.

- server/src/main/java/wap/web2/server/project/controller/ProjectController.java
- server/src/main/java/wap/web2/server/project/dto/RecruitmentDto.java
- server/src/main/java/wap/web2/server/project/dto/response/ProjectAppliesResponse.java
- server/src/main/java/wap/web2/server/project/entity/ProjectApply.java
- server/src/main/java/wap/web2/server/project/entity/ProjectRecruit.java
- server/src/main/java/wap/web2/server/project/entity/ProjectRecruitWish.java
- server/src/main/java/wap/web2/server/project/repository/ProjectRecruitRepository.java
- server/src/main/java/wap/web2/server/project/repository/ProjectRecruitWishRepository.java
- server/src/main/java/wap/web2/server/project/repository/ProjectRepository.java
- server/src/main/java/wap/web2/server/project/service/ApplyService.java
- closed: #276 
- 팀원 위시 리스트 엔티티 생성
> feat: 팀장이 선호하는 팀원 리스트를 등록하는 로직 구현

- server/src/main/java/wap/web2/server/teambuild/controller/TeamBuildController.java
- server/src/main/java/wap/web2/server/teambuild/dto/ApplyInfo.java
- server/src/main/java/wap/web2/server/teambuild/dto/RecruitInfo.java
- server/src/main/java/wap/web2/server/teambuild/dto/response/TeamBuildingResults.java
- server/src/main/java/wap/web2/server/teambuild/entity/Position.java
- server/src/main/java/wap/web2/server/teambuild/entity/ProjectApply.java
- server/src/main/java/wap/web2/server/teambuild/entity/ProjectRecruit.java
- server/src/main/java/wap/web2/server/teambuild/entity/ProjectRecruitWish.java
- server/src/main/java/wap/web2/server/teambuild/entity/Team.java
- server/src/main/java/wap/web2/server/teambuild/repository/ProjectApplyRepository.java
- server/src/main/java/wap/web2/server/teambuild/repository/ProjectRecruitRepository.java
- server/src/main/java/wap/web2/server/teambuild/repository/TeamRepository.java
- server/src/main/java/wap/web2/server/teambuild/service/ApplyService.java
- server/src/main/java/wap/web2/server/teambuild/service/TeamBuildService.java
- server/src/main/java/wap/web2/server/teambuild/service/impl/TeamBuilderImpl.java
- server/src/main/java/wap/web2/server/util/SemesterGenerator.java
- server/src/test/java/wap/web2/server/teambuild/service/SequentialTeamBuilderTest.java
- closed: #276 
- 메인 팀빌딩 알고리즘 impl 하기전 서비스 로직 작성
- 지금 열려있는 알고리즘pr의 매개변를 기준으로  회의한 내용에 맞는 스펙으로 구현함
- repo -> map 작업 
- map -> result 작업
> feat: apply와 recruit정보가 준비되었을 때 team build를 하는 로직 구현

- server/build.gradle
- server/src/main/java/wap/web2/server/ouath2/config/SecurityConfig.java
- server/src/main/java/wap/web2/server/project/controller/ProjectController.java
- server/src/main/java/wap/web2/server/project/dto/request/ProjectRequest.java
- server/src/main/java/wap/web2/server/project/repository/ProjectRepository.java
- server/src/main/java/wap/web2/server/project/service/ProjectService.java
- server/src/main/java/wap/web2/server/teambuild/controller/TeamBuildController.java
- server/src/main/java/wap/web2/server/teambuild/dto/TempProject.java
- server/src/main/java/wap/web2/server/teambuild/dto/request/ProjectAppliesRequest.java
- server/src/main/java/wap/web2/server/teambuild/dto/response/ProjectTemplate.java
- server/src/main/java/wap/web2/server/util/SemesterGenerator.java
- server/src/main/resources/templates/projects-application.html
- closed: #276 
1.
프로젝트 지원 페이지를 구현하였습니다. 모집중인 프로젝트 리스트를 확인하고, 지원서를 작성하여 장바구니에 담고, 제출할 수 있습니다.
2.
드래그 앤 드롭으로 선택한 프로젝트의 우선순위를 정하고, 제출하기 버튼을 누르면 최종적으로 alert 창으로 사용자에게 확인시킵니다.
3.
이 페이지가 React로 변경되기 전까지 사용될 에정인 코드로는 `ProjectTemplate`, `resources/templates/`, TeamBuildController의 일부 메서드, ProjectService의 getCurrentProjectRecruits 메서드입니다.
> 프로젝트 지원 페이지 구현

- client/src/App.js
- client/src/pages/menu/TeamBuildPage.js
- client/src/pages/menu/TeamBuildResultPage.js
- closed: #294 
- 팀 빌딩 페이지로 이동 추가
- 팀 빌딩 결과 페이지로 이동 추가
> feat: 팀 빌딩 관련 메뉴 추가

- server/src/main/java/wap/web2/server/teambuild/entity/Position.java
- server/src/main/resources/templates/projects-application.html
- #292 
동아리 임원진 요구사항에 맞게 IOS와 ANDROID를 APP으로 통일시키고, 사용되지 않는 포지션을 제거하였습니다.
또한 현재 활발히 모집중인 AI, GAME, EMBEDDED 개발자를 추가하였습니다.
- QA, PM, FULLSTACK, DATA 엔지니어 제거
- AI, GAME, EMBEDDED 개발자 추가
> 프로젝트 지원서에 사용되지 않는 포지션 정리

- server/src/main/java/wap/web2/server/teambuild/controller/TeamBuildControllerV1.java
- server/src/main/resources/file/applies.sql
- server/src/main/resources/file/recruits
- server/src/main/resources/templates/projects-application-for-leader.html
요구사항에 맞게 ANDROID와 IOS를 APP으로 통일시키고, PM을 삭제하고 EMBEDDED를 추가하였습니다.
변경된 포지션에 맞게 팀장의 희망 리스트를 수정하고, 프로젝트 지원 생성 쿼리를 수정하였습니다.
기존엔 8개의 포지션이어서 8로 나누었지만 7개의 포지션으로 바뀌면서 7로 나누도록 수정하였습니다.
실제로 테스트해보면 일부 팀은 구성이 잘 되지 않은 것을 확인할 수 있습니다. 이는 프로젝트 지원 생성 쿼리에서 모든 포지션별로 고르게 지원하였기 때문에 GAME팀에 프론트와 임베디드 등이 지원되었습니다. 하지만 팀장의 희망리스트에 capacity가 0이므로 선정되지 못해서 몇 명은 선택되지 못합니다.
이는 실제로 발생하지 않을 것으로 판단됩니다.!
결과를 통해 확인해보자면 ..
recruit 데이터에 6~10팀을 게임팀으로 임의 지정했습니다.
```
{
"projectId": 8,
"roasters": [
{ "position": "FRONTEND", "capacity": 0, "applicantIds": [] },
{ "position": "BACKEND",  "capacity": 0, "applicantIds": [] },
{ "position": "DESIGN",   "capacity": 1, "applicantIds": [1073, 1094, 1010, 1052, 1031] },
{ "position": "AI",       "capacity": 0, "applicantIds": [] },
{ "position": "APP",  "capacity": 0, "applicantIds": [] }, …
```
> 포지션에 APP, EMBEDDED 추가

- client/src/pages/menu/TeamBuildPage.js
- 쿠키가 사라지는 문제에 대응하기위해 get요청으로 변경
- 프론트 배포 테스트
- 페이지 이동 방식 변경
> fix: 페이지 이동 방식 변경

- server/src/main/java/wap/web2/server/teambuild/controller/TeamBuildControllerV1.java
/team-build 페이지에서 다시 /team-build로 redirect 하는 로직을 수정하여 Mixed-Content오류를 해결합니다.
> /team-build 에서 자신의 페이지로 redirect하지 않도록 변경

- server/src/main/resources/templates/projects-application-for-leader.html
- #303 
- cap 조절 이전에는 드래그로 등록이 불가능하게 해놓았습니다.
- cap을 조절한 포지션에서는 모든 지원자에대한 우선순위를 지정해야 제출이 가능하도록 검증했습니다.
> feat: 모집 페이지에서 사용자의 입력을 유도하는 기능 구현

- server/src/main/java/wap/web2/server/teambuild/dto/RecruitmentDto.java
- server/src/main/java/wap/web2/server/teambuild/entity/Position.java
- server/src/main/resources/templates/projects-application-for-leader.html
> feat: 모집을 한명도 하지 않아도 모집 제출 가능

- server/src/main/java/wap/web2/server/teambuild/controller/TeamBuildControllerV1.java
- server/src/main/java/wap/web2/server/teambuild/dto/RecruitmentDto.java
- server/src/main/java/wap/web2/server/teambuild/repository/ProjectApplyRepository.java
- server/src/main/java/wap/web2/server/teambuild/service/ApplyService.java
- server/src/main/resources/templates/already-applied.html
- closed: #317 
- 지원한 사용자가 또 지원하는 경우 뒤로가기 버튼과 적절한 안내가 있는 페이지로 이동시킵니다.
https://github.com/user-attachments/assets/d27d98c3-b984-45fc-a51e-2a431ebe89e3
> feat: 이미 지원한 사용자는 apply page에 접근할 수 없도록 검증 구현

- client/src/pages/menu/TeamBuildPage.js
> refactor: 필요없는 로직 공백처리

- server/src/main/java/wap/web2/server/teambuild/controller/TeamBuildControllerV2.java
- server/src/main/java/wap/web2/server/teambuild/repository/ProjectRecruitRepository.java
- server/src/main/java/wap/web2/server/teambuild/service/ApplyService.java
- 학기와 프로젝트 아이디를 기준으로 존재하는지 확인한다.
- 살짝 급하게 해서 잘못된 검증을 바로잡았습니다.
> fix: 이미 모집을 완료했는지 판단하는 메서드 변경

- server/build.gradle
- server/src/main/java/wap/web2/server/teambuild/controller/TeamBuildControllerV2.java
- server/src/main/java/wap/web2/server/teambuild/repository/ProjectApplyRepository.java
- server/src/main/java/wap/web2/server/teambuild/repository/ProjectRecruitRepository.java
- server/src/main/java/wap/web2/server/teambuild/service/ApplyService.java
- server/src/main/java/wap/web2/server/teambuild/service/TeamBuildExportService.java
> feat: 모집과 지원을 CSV로 변환하는 기능 구현

- server/src/main/java/wap/web2/server/project/controller/ProjectController.java
- closed: #343
- 프로젝트 상세 정보를 열람할 때 수정 권한이 있는 사람만 (삭제하기/수정하기) 버튼이 보이도록 하기위한 api 응답 스펙 조절
- isOwner 필드가 추가되었습니다.
- 브랜치를 실수해서 나머지(서비스 로직)는 메인에 바로 머지할게요
> fix: 프로젝트 상세 정보 필드에 isOwner 추가
